[package]
name = "dash-spv-ffi"
version = "0.1.6"
edition = "2018"

[dependencies]
byte = "0.2"
[dependencies.dash-spv-primitives]
git = "https://github.com/pankcuf/dash-spv-primitives"
branch = "master"
version = "^0.1"
[dependencies.dash-spv-models]
git = "https://github.com/pankcuf/dash-spv-models"
branch = "master"
version = "^0.1.4"
