[package]
name = "dash_mndiff"
version = "0.1.1"
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
byte = "0.2"

[dependencies.dash-spv-primitives]
git = "https://github.com/pankcuf/dash-spv-primitives"
branch = "master"
version = "0.1.2"

[build-dependencies]
cbindgen = "0.20.0"

[lib]
name = "dash_mndiff"
#crate-type = ["staticlib", "cdylib"]

[profile.release]
lto = "thin"
opt-level = 3
debug = true
