[package]
name = "masternodes-diff-processor"
version = "0.1.0"
edition = "2018"
build = "build.rs"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byte = "0.2"
sha2 = "0.9.8"
bitcoin_hashes = { version = "0.10.0", default-features = false }
bitcoinconsensus = { version = "0.19.0-3", optional = true }
hashbrown = { version = "0.8", optional = true }
secrets = "1.1.0"
blake3 = "1.1.0"
bls-signatures = "0.11.1"

[dev-dependencies]
secp256k1 = { version = "0.20.0", features = [ "recovery", "rand-std" ] }

[build-dependencies]
cbindgen = "0.20.0"

[lib]
name = "masternodesDiffProcessor"
crate-type = ["staticlib"]      # Creates dynamic lib


