[package]
name = "dash-spv-models"
version = "0.2.3"
edition = "2021"

[dependencies]
byte = "0.2"

[dependencies.dash-spv-primitives]
path = "../spv-primitives"

[lib]
name = "dash_spv_models"
#crate-type = ["staticlib", "cdylib"]

[profile.release]
lto = "thin"
opt-level = 3
debug = true
